---
title: "Capstone"
author: "Triet Tran"
date: "November 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("XML")
install.packages("rebus")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("stringr")
install.packages("lawstat")
install.packages("knitr")
install.packages("broom")
install.packages("survey")
install.packages("ResourceSelection")
```

```{r}
library(XML)
library(stringr)
library(rebus)
library(dplyr)
library(ggplot2)
library(lawstat)
library(broom)
library(knitr)
library(survey)
library(MASS)
library(ResourceSelection)
```

### Raw data

```{r}
setwd("C:/Users/Triet Tran/Desktop/Capstone")

ARI<-"http://www.espn.com/mlb/team/stats/batting/_/name/ari/year/2012/seasontype/2/split/37"
ATL<-"http://www.espn.com/mlb/team/stats/batting/_/name/atl/year/2012/seasontype/2/split/37"
BAL<-"http://www.espn.com/mlb/team/stats/batting/_/name/bal/year/2012/seasontype/2/split/37"
BOS<-"http://www.espn.com/mlb/team/stats/batting/_/name/bos/year/2012/seasontype/2/split/37"
CHC<-"http://www.espn.com/mlb/team/stats/batting/_/name/chc/year/2012/seasontype/2/split/37"
CHW<-"http://www.espn.com/mlb/team/stats/batting/_/name/chw/year/2012/seasontype/2/split/37"
CIN<-"http://www.espn.com/mlb/team/stats/batting/_/name/cin/year/2012/seasontype/2/split/37"
CLE<-"http://www.espn.com/mlb/team/stats/batting/_/name/cle/year/2012/seasontype/2/split/37"
COL<-"http://www.espn.com/mlb/team/stats/batting/_/name/col/year/2012/seasontype/2/split/37"
DET<-"http://www.espn.com/mlb/team/stats/batting/_/name/det/year/2012/seasontype/2/split/37"
HOU<-"http://www.espn.com/mlb/team/stats/batting/_/name/hou/year/2012/seasontype/2/split/37"
KC<-"http://www.espn.com/mlb/team/stats/batting/_/name/kc/year/2012/seasontype/2/split/37"
LAA<-"http://www.espn.com/mlb/team/stats/batting/_/name/laa/year/2012/seasontype/2/split/37"
LAD<-"http://www.espn.com/mlb/team/stats/batting/_/name/lad/year/2012/seasontype/2/split/37"
MIA<-"http://www.espn.com/mlb/team/stats/batting/_/name/mia/year/2012/seasontype/2/split/37"
MIL<-"http://www.espn.com/mlb/team/stats/batting/_/name/mil/year/2012/seasontype/2/split/37"
MIN<-"http://www.espn.com/mlb/team/stats/batting/_/name/min/year/2012/seasontype/2/split/37"
NYM<-"http://www.espn.com/mlb/team/stats/batting/_/name/nym/year/2012/seasontype/2/split/37"
NYY<-"http://www.espn.com/mlb/team/stats/batting/_/name/nyy/year/2012/seasontype/2/split/37"
OAK<-"http://www.espn.com/mlb/team/stats/batting/_/name/oak/year/2012/seasontype/2/split/37"
PHI<-"http://www.espn.com/mlb/team/stats/batting/_/name/phi/year/2012/seasontype/2/split/37"
PIT<-"http://www.espn.com/mlb/team/stats/batting/_/name/pit/year/2012/seasontype/2/split/37"
SD<-"http://www.espn.com/mlb/team/stats/batting/_/name/sd/year/2012/seasontype/2/split/37"
SF<-"http://www.espn.com/mlb/team/stats/batting/_/name/sf/year/2012/seasontype/2/split/37"
SEA<-"http://www.espn.com/mlb/team/stats/batting/_/name/sea/year/2012/seasontype/2/split/37"
STL<-"http://www.espn.com/mlb/team/stats/batting/_/name/stl/year/2012/seasontype/2/split/37"
TB<-"http://www.espn.com/mlb/team/stats/batting/_/name/tb/year/2012/seasontype/2/split/37"
TEX<-"http://www.espn.com/mlb/team/stats/batting/_/name/tex/year/2012/seasontype/2/split/37"
TOR<-"http://www.espn.com/mlb/team/stats/batting/_/name/tor/year/2012/seasontype/2/split/37"
WSH<-"http://www.espn.com/mlb/team/stats/batting/_/name/wsh/year/2012/seasontype/2/split/37"
```

### Data collection function

```{r}
create_data<-function(link){
for(i in 2002:2017){
  for(j in c(37,38,39,185,94)){
pattern_year<-capture (DGT %R% DGT %R% DGT %R% DGT)
link<-gsub(pattern_year, i, link)
pattern_situ<-capture ("t/" %R% one_or_more(DGT))
temp_link<-str_replace(link,pattern_situ,"t/")
link<-paste(temp_link,j,sep="")
df <- readHTMLTable(gsub(pattern_year, i, link), header=T, which=1,skip.rows=1, stringsAsFactors=T, na.rm=T)
df$YEAR=i
if(j==37){
df$SITU="NO"
} else if(j==38){
  df$SITU="RO"
} else if(j==39){
  df$SITU="SP"
} else if(j==185){
  df$SITU="SP2O"
} else {
  df$SITU="BL"
}
write.table(df, file="storage.csv", append=T, sep=",", dec=".", col.names = NA, row.names = T)
  }
}
data<-read.table("storage.csv", sep=",", header=T)
unlink("storage.csv")
data$OWAR<-NULL
data$SB<-NULL
data$X.1<-NULL
data$X<-NULL
data<-subset(data, data$NAME != "NAME" & data$NAME != "Totals" & data$NAME != "Opponents")
return(data)
}
```

```{r}
#List of teams: ARI,ATL,BAL,BOS,CHC,CHW,CIN,CLE,COL,DET,HOU,KC,LAA,LAD,MIA,MIL,MIN,NYM,NYY,OAK,PHI,PIT,SD,SF,SEA,STL,TB,TEX,TOR,WSH
data1<-create_data(ARI)
data1$TEAM<-"ARI"
data2<-create_data(ATL)
data2$TEAM<-"ATL"
data3<-create_data(BAL)
data3$TEAM<-"BAL"
data4<-create_data(BOS)
data4$TEAM<-"BOS"
data5<-create_data(CHC)
data5$TEAM<-"CHC"
data6<-create_data(CHW)
data6$TEAM<-"CHW"
data7<-create_data(CIN)
data7$TEAM<-"CIN"
data8<-create_data(CLE)
data8$TEAM<-"CLE"
data9<-create_data(COL)
data9$TEAM<-"COL"
data10<-create_data(DET)
data10$TEAM<-"DET"
data11<-create_data(HOU)
data11$TEAM<-"HOU"
data12<-create_data(KC)
data12$TEAM<-"KC"
data13<-create_data(LAA)
data13$TEAM<-"LAA"
data14<-create_data(LAD)
data14$TEAM<-"LAD"
data15<-create_data(MIA)
data15$TEAM<-"MIA"
data16<-create_data(MIL)
data16$TEAM<-"MIL"
data17<-create_data(MIN)
data17$TEAM<-"MIN"
data18<-create_data(NYM)
data18$TEAM<-"NYM"
data19<-create_data(NYY)
data19$TEAM<-"NYY"
data20<-create_data(OAK)
data20$TEAM<-"OAK"
data21<-create_data(PHI)
data21$TEAM<-"PHI"
data22<-create_data(PIT)
data22$TEAM<-"PIT"
data23<-create_data(SD)
data23$TEAM<-"SD"
data24<-create_data(SF)
data24$TEAM<-"SF"
data25<-create_data(SEA)
data25$TEAM<-"SEA"
data26<-create_data(STL)
data26$TEAM<-"STL"
data27<-create_data(TB)
data27$TEAM<-"TB"
data28<-create_data(TEX)
data28$TEAM<-"TEX"
data29<-create_data(TOR)
data29$TEAM<-"TOR"
data30<-create_data(WSH)
data30$TEAM<-"WSH"
data<-rbind(data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30)
save(data,file="data.rda")
```

```{r}
create_overall<-function(link){
unlink("storage.csv")
for(i in 2015:2017){
pattern_year<-capture (DGT %R% DGT %R% DGT %R% DGT)
link<-gsub(pattern_year, i, link)
df <- readHTMLTable(link, header=T, which=1,skip.rows=1, stringsAsFactors=T, na.rm=T)
df$YEAR=i
write.table(df, file="storage.csv", append=T, sep=",", dec=".", col.names = NA, row.names = T)
data<-read.table("storage.csv", sep=",", header=T)
}
data$OWAR<-NULL
data$X<-NULL
data<-read.table("storage.csv", sep=",", header=T)
data<-subset(data, data$NAME != "NAME" & data$NAME != "Totals" & data$NAME != "Opponents")
return(data)
}
```

```{r}
ARI<-"http://www.espn.com/mlb/team/stats/batting/_/name/ari/year/2015"
ATL<-"http://www.espn.com/mlb/team/stats/batting/_/name/atl/year/2015"
BAL<-"http://www.espn.com/mlb/team/stats/batting/_/name/bal/year/2015"
BOS<-"http://www.espn.com/mlb/team/stats/batting/_/name/bos/year/2015"
CHC<-"http://www.espn.com/mlb/team/stats/batting/_/name/chc/year/2015"
CHW<-"http://www.espn.com/mlb/team/stats/batting/_/name/chw/year/2015"
CIN<-"http://www.espn.com/mlb/team/stats/batting/_/name/cin/year/2015"
CLE<-"http://www.espn.com/mlb/team/stats/batting/_/name/cle/year/2015"
COL<-"http://www.espn.com/mlb/team/stats/batting/_/name/col/year/2015"
DET<-"http://www.espn.com/mlb/team/stats/batting/_/name/det/year/2015"
HOU<-"http://www.espn.com/mlb/team/stats/batting/_/name/hou/year/2015"
KC<-"http://www.espn.com/mlb/team/stats/batting/_/name/kc/year/2015"
LAA<-"http://www.espn.com/mlb/team/stats/batting/_/name/laa/year/2015"
LAD<-"http://www.espn.com/mlb/team/stats/batting/_/name/lad/year/2015"
MIA<-"http://www.espn.com/mlb/team/stats/batting/_/name/mia/year/2015"
MIL<-"http://www.espn.com/mlb/team/stats/batting/_/name/mil/year/2015"
MIN<-"http://www.espn.com/mlb/team/stats/batting/_/name/min/year/2015"
NYM<-"http://www.espn.com/mlb/team/stats/batting/_/name/nym/year/2015"
NYY<-"http://www.espn.com/mlb/team/stats/batting/_/name/nyy/year/2015"
OAK<-"http://www.espn.com/mlb/team/stats/batting/_/name/oak/year/2015"
PHI<-"http://www.espn.com/mlb/team/stats/batting/_/name/phi/year/2015"
PIT<-"http://www.espn.com/mlb/team/stats/batting/_/name/pit/year/2015"
SD<-"http://www.espn.com/mlb/team/stats/batting/_/name/sd/year/2015"
SF<-"http://www.espn.com/mlb/team/stats/batting/_/name/sf/year/2015"
SEA<-"http://www.espn.com/mlb/team/stats/batting/_/name/sea/year/2015"
STL<-"http://www.espn.com/mlb/team/stats/batting/_/name/stl/year/2015"
TB<-"http://www.espn.com/mlb/team/stats/batting/_/name/tb/year/2015"
TEX<-"http://www.espn.com/mlb/team/stats/batting/_/name/tex/year/2015"
TOR<-"http://www.espn.com/mlb/team/stats/batting/_/name/tor/year/2015"
WSH<-"http://www.espn.com/mlb/team/stats/batting/_/name/wsh/year/2015"
#List of teams: ARI,ATL,BAL,BOS,CHC,CHW,CIN,CLE,COL,DET,HOU,KC,LAA,LAD,MIA,MIL,MIN,NYM,NYY,OAK,PHI,PIT,SD,SF,SEA,STL,TB,TEX,TOR,WSH
data1<-create_overall(ARI)
data1$TEAM<-"ARI"
data2<-create_overall(ATL)
data2$TEAM<-"ATL"
data3<-create_overall(BAL)
data3$TEAM<-"BAL"
data4<-create_overall(BOS)
data4$TEAM<-"BOS"
data5<-create_overall(CHC)
data5$TEAM<-"CHC"
data6<-create_overall(CHW)
data6$TEAM<-"CHW"
data7<-create_overall(CIN)
data7$TEAM<-"CIN"
data8<-create_overall(CLE)
data8$TEAM<-"CLE"
data9<-create_overall(COL)
data9$TEAM<-"COL"
data10<-create_overall(DET)
data10$TEAM<-"DET"
data11<-create_overall(HOU)
data11$TEAM<-"HOU"
data12<-create_overall(KC)
data12$TEAM<-"KC"
data13<-create_overall(LAA)
data13$TEAM<-"LAA"
data14<-create_overall(LAD)
data14$TEAM<-"LAD"
data15<-create_overall(MIA)
data15$TEAM<-"MIA"
data16<-create_overall(MIL)
data16$TEAM<-"MIL"
data17<-create_overall(MIN)
data17$TEAM<-"MIN"
data18<-create_overall(NYM)
data18$TEAM<-"NYM"
data19<-create_overall(NYY)
data19$TEAM<-"NYY"
data20<-create_overall(OAK)
data20$TEAM<-"OAK"
data21<-create_overall(PHI)
data21$TEAM<-"PHI"
data22<-create_overall(PIT)
data22$TEAM<-"PIT"
data23<-create_overall(SD)
data23$TEAM<-"SD"
data24<-create_overall(SF)
data24$TEAM<-"SF"
data25<-create_overall(SEA)
data25$TEAM<-"SEA"
data26<-create_overall(STL)
data26$TEAM<-"STL"
data27<-create_overall(TB)
data27$TEAM<-"TB"
data28<-create_overall(TEX)
data28$TEAM<-"TEX"
data29<-create_overall(TOR)
data29$TEAM<-"TOR"
data30<-create_overall(WSH)
data30$TEAM<-"WSH"
data_overall<-rbind(data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30)
save(data,file="data_overall.rda")
```

```{r}
load("data.rda")
load("data_overall.rda")
```

# Convert factor variables to numeric

```{r}
data_temp<-data[,c("NAME","SITU")]
indx <- sapply(data, is.factor)
data[indx] <- lapply(data[indx], function(x) as.numeric(as.character(x)))
data$NAME=NULL
data$SITU=NULL
data<-cbind(data_temp,data)
```

```{r}
data_temp<-data_overall[,c("NAME","X")]
indx <- sapply(data_overall, is.factor)
data_overall[indx] <- lapply(data_overall[indx], function(x) as.numeric(as.character(x)))
data_overall$NAME=NULL
data_overall$X=NULL
data_overall<-cbind(data_temp,data_overall)
data_overall$X=NULL

data_overall$matchingID<-paste(data_overall$NAME," ",data_overall$YEAR)
```

### Sub-data based on situational hitting

#None on(NO): 37
#Runners on(RO): 38
#Scoring positions(SP): 39
#Scoring positions /w 2 outs (SP2O): 185
#Bases loaded(BL): 94

```{r}
qplot(data$AB, geom="histogram",
      binwidth=10,
      main = "Total at-bats", 
      xlab = "At-bats",  
      fill=I("red"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,508))
```

```{r}
#Function to omit batters with too few at-bats
omit_min_AB<-function(dataset,situ){
  dataset<-subset(dataset, dataset$SITU==situ)
  dataset<-subset(dataset, dataset$AB>=quantile(dataset$AB,.5))
  return(dataset)
}
data_NO<-omit_min_AB(data,"NO")
data_RO<-omit_min_AB(data,"RO")
data_SP<-omit_min_AB(data,"SP")
data_SP2O<-omit_min_AB(data,"SP2O")
data_BL<-omit_min_AB(data,"BL")
```

### Analysis

```{r}
totalab<-sum(data_NO$AB,data_RO$AB,data_SP$AB,data_SP2O$AB,data_BL$AB)
totalab
sum(data_NO$AB)/totalab
sum(data_RO$AB)/totalab
sum(data_SP$AB)/totalab
sum(data_SP2O$AB)/totalab
sum(data_BL$AB)/totalab
```

```{r}
# Function to calculate weighted variance 
weighted.var <- function(x, w, na.rm = FALSE) {
    if (na.rm) {
        w <- w[i <- !is.na(x)]
        x <- x[i]
    }
    sum.w <- sum(w)
    sum.w2 <- sum(w^2)
    mean.w <- sum(x * w) / sum(w)
    (sum.w / (sum.w^2 - sum.w2)) * sum(w * (x - mean.w)^2, na.rm =
na.rm)
}

weighted.var(data$BA, data$AB)
weighted.mean(data$BA, data$AB)
```

```{r}
qplot(data_NO$BA, geom="histogram",
      binwidth=0.01,
      main = "Batting average with nobody on", 
      xlab = "BA",  
      fill=I("blue"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,.5))
qplot(data_SP2O$BA, geom="histogram",
      binwidth=0.01,
      main = "Batting Average with RISP with 2 outs", 
      xlab = "BA",  
      fill=I("blue"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,.5))
```

```{r}
#F test for difference in variance
var.test(data_NO$BA, data_SP2O$BA)
```

```{r}
qplot(data_NO$BA, geom="histogram",
      binwidth=0.01,
      main = "Batting average with nobody on", 
      xlab = "BA",  
      fill=I("blue"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,.5))
qplot(data_SP$BA, geom="histogram",
      binwidth=0.01,
      main = "Batting Average with RISP", 
      xlab = "BA",  
      fill=I("blue"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,.5))
```

```{r}
var.test(data_NO$OPS, data_SP$OPS)
mean(data_NO$OPS)
mean(data_SP$OPS)
mean(data_SP2O$OPS)
summary(data$OPS)
```

```{r}
qplot(data_NO$OPS, geom="histogram",
      binwidth=0.02,
      main = "OPS with nobody on", 
      xlab = "OPS",  
      fill=I("green"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,2))
qplot(data_SP2O$OPS, geom="histogram",
      binwidth=0.02,
      main = "OPS with RISP with 2 outs", 
      xlab = "OPS",  
      fill=I("green"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,2))
qplot(data_SP$OPS, geom="histogram",
      binwidth=0.02,
      main = "OPS with RISP", 
      xlab = "OPS",  
      fill=I("green"), 
      col=I("black"), 
      alpha=I(.2),
      xlim=c(0,2))
```

```{r}
data_NO$matchingID<-paste(data_NO$NAME," ",data_NO$YEAR)
data_NO$OPS_NO<-data_NO$OPS
data_NO_sub<-subset(data_NO, select = c(matchingID, OPS_NO,AB))
data_NO_sub_unique_1<-data_NO_sub %>% group_by(matchingID) %>%
        summarise_each(funs(weighted.mean(., AB,na.rm=T)),OPS_NO)
data_NO_sub_unique_2<-data_NO_sub %>% group_by(matchingID) %>%
        summarise_each(funs(sum),AB)
data_NO_unique<-left_join(data_NO_sub_unique_1,data_NO_sub_unique_2,by="matchingID")

data_SP$matchingID<-paste(data_SP$NAME," ",data_SP$YEAR)
data_SP$OPS_SP<-data_SP$OPS
data_SP_sub<-subset(data_SP, select = c(matchingID, OPS_SP,AB))
data_SP_sub_unique_1<-data_SP_sub %>% group_by(matchingID) %>%
        summarise_each(funs(weighted.mean(., AB,na.rm=T)),OPS_SP)
data_SP_sub_unique_2<-data_SP_sub %>% group_by(matchingID) %>%
        summarise_each(funs(sum),AB)
data_SP_unique<-left_join(data_SP_sub_unique_1,data_SP_sub_unique_2,by="matchingID")

data_clutch<-left_join(data_NO_unique,data_SP_unique,by="matchingID")
data_clutch<-subset(data_clutch,!is.na(OPS_SP))
data_clutch$diffOPS=data_clutch$OPS_SP-data_clutch$OPS_NO
data_clutch$AB<-data_clutch$AB.x+data_clutch$AB.y
quantile(data_clutch$AB,.25)
data_clutch_158<-subset(data_clutch,data_clutch$AB>=158)
```


```{r}
top_fifty <- data_clutch %>%
         filter(rank(desc(OPS_SP))<=50)
top_fifty_158 <- data_clutch_158 %>%
         filter(rank(desc(OPS_SP))<=50)
 
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Albert Pujols"))
    Albert_Pujols<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Barry Bonds"))
    Barry_Bonds<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Freddie Freeman"))
    Freddie_Freeman<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Joey Votto"))
    Joey_Votto<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Lance Berkman"))
    Lance_Berkman<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Manny Ramirez"))
    Manny_Ramirez<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Mark Teix"))
    Mark_Texeira<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Miguel Cabrera"))
    Miguel_Cabrera<-storage$OPS_SP
storage<-data_clutch %>%
    filter(str_detect(matchingID, "Nolan Arenado"))
    Nolan_Arenado<-storage$OPS_SP    

boxplot(Albert_Pujols,Barry_Bonds,Freddie_Freeman,Joey_Votto,Lance_Berkman,Manny_Ramirez,Mark_Texeira,Miguel_Cabrera,Nolan_Arenado,col=c("red","green","yellow","blue","brown","purple","orange","grey","pink"),names=c("Pujols","Bonds","Freeman","Votto","Berkman","Ramirez","Texeira","Cabrera","Arenado"))

mid<-mean(data_clutch$OPS_SP) 

abline(h=mid,col="red")

t.test(Mark_Texeira,mu=mid,alternative = "greater")
```
    
```{r}  
    plot(data_clutch$OPS_NO,data_clutch$OPS_SP, 
         pch = 16, 
         cex = .11, 
         col = "blue", 
         main = "Clutch OPS AGAINST Non-clutch OPS", 
         xlab = "Non-clutch OPS", 
         ylab = "Clutch OPS")
    model<-lm(data_clutch$OPS_SP ~ data_clutch$OPS_NO)
    abline(model,col="red")
```

```{r}
top_fifty_158 <- data_clutch_158 %>%
         filter(rank(desc(diffOPS))<=50)
```

```{r}
data_overall_clutch_158<-left_join(data_clutch_158,data_overall,by="matchingID")
save(data_overall_clutch_158,file="data_overall_clutch_158.rda")
```

```{r}
load("data_overall_clutch_158.rda")
data_overall_clutch_158<-subset(data_overall_clutch_158,!is.na(GP))
```

```{r}
qqnorm(data_overall_clutch_158$OPS_SP)
qqline(data_overall_clutch_158$OPS_SP, col = "red")
```

```{r}
m1 <- lm(OPS_SP~R, data=data_overall_clutch_158)
m2 <- lm(OPS_SP~X2B, data=data_overall_clutch_158)
m3 <- lm(OPS_SP~X3B, data=data_overall_clutch_158)
m4 <- lm(OPS_SP~HR, data=data_overall_clutch_158)
m5 <- lm(OPS_SP~RBI, data=data_overall_clutch_158)
m6 <- lm(OPS_SP~TB, data=data_overall_clutch_158)
m7 <- lm(OPS_SP~BB, data=data_overall_clutch_158)
m8 <- lm(OPS_SP~SO, data=data_overall_clutch_158)
m9 <- lm(OPS_SP~BA, data=data_overall_clutch_158)
m10 <- lm(OPS_SP~OBP, data=data_overall_clutch_158)
m11 <- lm(OPS_SP~SLG, data=data_overall_clutch_158)
m12 <- lm(OPS_SP~H, data=data_overall_clutch_158)

t1 <- tidy(m1, conf.int=T)[-1,-c(3,4)]
t2 <- tidy(m2, conf.int=T)[-1,-c(3,4)]
t3 <- tidy(m3, conf.int=T)[-1,-c(3,4)]
t4 <- tidy(m4, conf.int=T)[-1,-c(3,4)]
t5 <- tidy(m5, conf.int=T)[-1,-c(3,4)]
t6 <- tidy(m6, conf.int=T)[-1,-c(3,4)]
t7 <- tidy(m7, conf.int=T)[-1,-c(3,4)]
t8 <- tidy(m8, conf.int=T)[-1,-c(3,4)]
t9 <- tidy(m9, conf.int=T)[-1,-c(3,4)]
t10 <- tidy(m10, conf.int=T)[-1,-c(3,4)]
t11 <- tidy(m11, conf.int=T)[-1,-c(3,4)]
t12 <- tidy(m12, conf.int=T)[-1,-c(3,4)]

knitr::kable(bind_rows(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12))
```

```{r}
summary(lm(HR~SO, data=data_overall_clutch_158))
```

```{r}
full_model<-glm(OPS_SP~SO+RBI+OBP+SLG, data=data_overall_clutch_158)
step.aic.b<-stepAIC(full_model, direction="backward", trace=FALSE, k=10);
summary(step.aic.b)
hoslem.test(data_overall_clutch_158$OPS_SP, fitted(full_model), g=10)
plot(full_model)
```

```{r}
s.model<-lm(RBI~SLG, data=data_overall_clutch_158)
summary(s.model)
```

```{r}
link<-"http://www.espn.com/mlb/stats/team/_/stat/batting/year/2000/split/39"
create_team<-function(link){
unlink("storage.csv")
for(i in 2000:2017){
pattern_year<-capture (DGT %R% DGT %R% DGT %R% DGT)
link<-gsub(pattern_year, i, link)
df <- readHTMLTable(link, header=T, which=1,skip.rows=1, stringsAsFactors=T, na.rm=T)
df$YEAR=i
write.table(df, file="storage.csv", append=T, sep=",", dec=".", col.names = NA, row.names = T)
data<-read.table("storage.csv", sep=",", header=T)
}
data<-subset(data, data$TEAM != "GP" & data$TEAM != "161" & data$TEAM != "162" & data$TEAM != "TEAM")
data$RK<-NULL
data$X<-NULL
return(data)
}
data_team<-create_team(link)
```

```{r}
link<-"http://www.espn.com/mlb/stats/team/_/stat/pitching/year/2016"
data_win<-create_team(link)
```

```{r}
data_team$matchingID<-paste(data_team$TEAM," ",data_team$YEAR)
data_win$matchingID<-paste(data_win$TEAM," ",data_win$YEAR)
data_win<-subset(data_win, select = c(matchingID, W))
data_team<-left_join(data_team,data_win,by="matchingID")

data_temp<-data_team[,c("matchingID","TEAM")]
indx <- sapply(data_team, is.factor)
data_team[indx] <- lapply(data_team[indx], function(x) as.numeric(as.character(x)))
data_team$matchingID=NULL
data_team$TEAM=NULL
data<-cbind(data_temp,data_team)
```

```{r}
team_model<-glm(W~OPS,data=data_team)
summary(team_model)
```